spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=true&serverTimezone=UTC
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger API Docs (Enabled or restricted, we will leave it enabled for portfolio assessment)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT properties
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION}

# Logging Configuration
logging.config=classpath:logback-spring.xml

# Max Upload Size
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
